import Head from 'next/head'
import { AiFillInstagram, AiFillFacebook, AiFillLinkedin } from 'react-icons/ai';
import React, { useState, useEffect } from 'react';
import { FaArrowUp } from 'react-icons/fa';
import Image from 'next/image';
import NextLink from 'next/link';
import { Link } from "react-scroll";
import Typewriter from "typewriter-effect";
import 'react-circular-progressbar/dist/styles.css';
import { CircularProgressbar, buildStyles } from 'react-circular-progressbar';

export default function Home() {

  const [scrolling, setScrolling] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 200) {
        setScrolling(true);
      } else {
        setScrolling(false);
      }
    };

    window.addEventListener('scroll', handleScroll);
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  return (
    <div className='backgroundimg'>
      <Head>
        <title>Chai Qi Qian Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navigation Bar */}
      <div className="fixed top-0 w-full z-50">
        <nav className="py-4 px-5 flex justify-between animate-slide-in-top text-base md:text-xl bg-white border-b-2 border-gray-500">
          <div className='flex text-xl md:text-3xl cursor-pointer' onClick={() => window.location.reload()}>Chai Qi Qian • Portfolio </div>
          {/* menu navigation bar */}
          <div className='menu' onClick={() => {
            setMenuOpen(!menuOpen)
          }}>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
          </div>
          <ul className={menuOpen ? "open" : ""}>
            {/* normal navigation bar */}
            <li className='flex md:mt-2 mt-1'>
              <Link
                to="about"
                spy={true}
                smooth={true}
                offset={-70}
                duration={500}
                className="ml-5 cursor-pointer"
                onClick={() => setMenuOpen(false)}
              >
                About
              </Link>
              <Link
                to="projects"
                spy={true}
                smooth={true}
                offset={-70}
                duration={500}
                className="ml-5 cursor-pointer"
                onClick={() => setMenuOpen(false)}
              >
                Projects
              </Link>
              <Link
                to="skills"
                spy={true}
                smooth={true}
                offset={-70}
                duration={500}
                className="ml-5 cursor-pointer"
                onClick={() => setMenuOpen(false)}
              >
                Skills
              </Link>
              <Link
                to="life"
                spy={true}
                smooth={true}
                offset={-70}
                duration={500}
                className="ml-5 cursor-pointer"
                onClick={() => setMenuOpen(false)}
              >
                Life
              </Link>
              <a href="mailto: qichaiqian27@outlook.com" className="ml-5">Contact</a>
              <a href="/ChaiQiQian.pdf" target="_blank" rel="noopener noreferrer" className="ml-5">Resume</a>
            </li>
          </ul>
        </nav>
      </div>

      <main className='md:px-14 px-5'>
        {/* Profile Image and Greeting */}
        <section>
          <div className='flex flex-col md:flex-row justify-center items-center animate-slide-in-top mt-20 '>
            <div>
              <Image src="/cqq.png" alt="" width={330} height={330} className='h-54 w-44 md:h-64 md:w-56 lg:h-96 lg:w-72 mx-auto md:mx-0' />
              <div className='flex justify-center items-center mt-2'>
                <a href="https://www.instagram.com/qiqian1227/" target="_blank" rel="noopener noreferrer" className='md:mt-3 mt-1'>
                  <AiFillInstagram size={40} className='md:w-10 md:h-10 w-8 h-8 hover:scale-[110%] transition-transform' />
                </a>
                <a href="https://www.facebook.com/qiqianchai/" target="_blank" rel="noopener noreferrer" className='md:mt-3 mt-1 ml-10'>
                  <AiFillFacebook size={40} className='md:w-10 md:h-10 w-8 h-8  hover:scale-[110%] transition-transform' />
                </a>
                <a href="https://www.linkedin.com/in/chai-qi-qian-a5094520a/" target="_blank" rel="noopener noreferrer" className='md:mt-3 mt-1 ml-10'>
                  <AiFillLinkedin size={40} className='md:w-10 md:h-10 w-8 h-8 hover:scale-[110%] transition-transform' />
                </a>
              </div>
            </div>
            <div className='mobile text-center md:text-left text-blue-500 text-2xl lg:text-4xl ml-16' style={{ width: '350px', height: '100px' }}>
              <p className='text-2xl lg:text-4xl text-black'>Hey! It&apos;s Me 👋👋</p>
              <p className='text-3xl lg:text-5xl text-black'>Chai Qi Qian</p>
              <p className='text-2xl lg:text-4xl text-black'>I am a </p>
              <Typewriter
                options={{
                  strings: [
                    "Front End Developer",
                    "Back End Developer",
                    "Full Stack Developer",
                  ],
                  autoStart: true,
                  loop: true,
                }}
              />
            </div>
          </div>
        </section>

        <section id='about'>
          <div className='shadow-lg p-5 md:p-10 rounded-xl my-1 '>
            <h3 className='text-xl md:text-2xl text-center py-5 text-blue-500 font-bold'>About Me</h3>
            <div className='grid md:grid-cols-2 gap-3'>
              <div className='bg-gray-100 p-6 rounded-lg hover:scale-[102%]  transition-transform'>
                <h4 className='text-base md:text-lg font-semibold mb-2 text-center md:text-left'>Educations</h4>
                <div className='space-y-4'>
                  <div className='flex items-center hover:scale-[102%] transition-transform'>
                    <div className='md:w-8 md:h-8 w-5 h-5 bg-blue-500 rounded-full'></div>
                    <div className='ml-4 '>
                      <h5 className='text-sm md:text-base font-semibold'>Bachelor of Computing Science</h5>
                      <p className='text-xs md:text-base text-gray-600'>Taylor&apos;s University</p>
                      <p className='text-xs md:text-base text-gray-600'>Mar 2021 - Mar 2024</p>
                      <p className='text-xs md:text-base'>Data Science & Artificial Intelligence</p>
                    </div>
                  </div>
                  <div className='flex items-center hover:scale-[102%] transition-transform'>
                    <div className='md:w-8 md:h-8 w-5 h-5 bg-blue-500 rounded-full'></div>
                    <div className='ml-4'>
                      <h5 className='text-sm md:text-base font-semibold'>Foundation in Computing</h5>
                      <p className='text-xs md:text-base text-gray-600'>Taylor&apos;s College</p>
                      <p className='text-xs md:text-base text-gray-600'>Mar 2020 - Mar 2021</p>
                    </div>
                  </div>
                  <div className='flex items-center hover:scale-[102%] transition-transform'>
                    <div className='md:w-8 md:h-8 w-5 h-5 bg-blue-500 rounded-full'></div>
                    <div className='ml-4'>
                      <h5 className='text-sm md:text-base font-semibold'>Sijil Pelajaran Malaysia (SPM)</h5>
                      <p className='text-xs md:text-base text-gray-600'>SMJK (C) Chung Hwa</p>
                      <p className='text-xs md:text-base text-gray-600'>Jan 2015 - Jan 2019</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className='bg-gray-100 p-6 rounded-lg hover:scale-[102%] transition-transform'>
                <h4 className='text-base md:text-lg font-semibold mb-2 text-center md:text-left'>Certifications</h4>
                <div>
                  <a href='https://sdtaylorsedu-my.sharepoint.com/:i:/g/personal/qiqian_chai_sd_taylors_edu_my/Eeu_XIweezVIknJNdJ8pr8wB-TqQA9Z4LE8q7wSBzJv1ug?e=c5EH4g' target="_blank" rel="noopener noreferrer">
                    <div className='bg-white p-4 rounded-lg shadow-md hover:scale-[102%] transition-transform' >
                      <h5 className='text-sm md:text-base font-semibold mb-1'>Huawei Data Communication & Network Technology</h5>
                      <div className='flex justify-between'>
                        <p className='text-xs md:text-sm text-gray-600'>September 2021</p>
                        <p className='text-xs md:text-sm text-gray-600'>View</p>
                      </div>
                    </div>
                  </a>
                  <a href='https://sdtaylorsedu-my.sharepoint.com/:i:/g/personal/qiqian_chai_sd_taylors_edu_my/EYAARo2lPT1EkGxSnwDJZOYB37dX9_ExLUwnSN_p8uJubQ?e=rAohdO' target="_blank" rel="noopener noreferrer">
                    <div className='bg-white p-4 rounded-lg shadow-md hover:scale-[102%] transition-transform mt-2' >
                      <h5 className='text-sm md:text-base font-semibold mb-1'>Salesforce Foundation</h5>
                      <div className='flex justify-between'>
                        <p className='text-xs md:text-sm text-gray-600'>Jul 2021</p>
                        <p className='text-xs md:text-sm text-gray-600'>View</p>
                      </div>
                    </div>
                  </a>
                  <a href='https://sdtaylorsedu-my.sharepoint.com/:b:/g/personal/qiqian_chai_sd_taylors_edu_my/EeTCd-9pWVVBlvAwX6a0GWQBjIncL5qu6Mv-NldmI7VdyA?e=kSOwf6' target="_blank" rel="noopener noreferrer">
                    <div className='bg-white p-4 rounded-lg shadow-md hover:scale-[102%] transition-transform mt-2' >
                      <h5 className='text-sm md:text-base font-semibold mb-1'>Oracle Java Foundation</h5>
                      <div className='flex justify-between'>
                        <p className='text-xs md:text-sm text-gray-600'>Jun 2021</p>
                        <p className='text-xs md:text-sm text-gray-600'>View</p>
                      </div>
                    </div>
                  </a>
                </div>
              </div>
              <div className='bg-gray-100 p-6 rounded-lg hover:scale-[102%] transition-transform'>
                <h4 className='text-base md:text-lg font-semibold mb-2 text-center md:text-left'>Languages</h4>
                <div className='flex items-center justify-center space-x-5 md:space-x-10'>
                  <div className='text-center hover:scale-[102%] transition-transform'>
                    <span className='text-base md:text-lg'>English</span>
                    <div style={{ position: 'relative', width: '65px', height: '65px' }} className='space-y-2 group'>
                      <div
                        style={{
                          position: 'absolute',
                          top: '50%',
                          left: '50%',
                          transform: 'translate(-50%, -50%)',
                          zIndex: 1,
                        }}
                      >
                        80%
                      </div>
                      <div>
                        <CircularProgressbar
                          value={80}
                          styles={buildStyles({
                            textColor: '#000',
                            pathColor: '#03A9F4',
                            trailColor: '#D1D5DB',
                          })}
                          className="group-hover:rotate-[360deg] duration-700"
                        />
                      </div>
                    </div>
                  </div>
                  <div className='text-center hover:scale-[102%] transition-transform'>
                    <span className='text-base md:text-lg'>Malay</span>
                    <div style={{ position: 'relative', width: '65px', height: '65px' }} className='space-y-2 group'>
                      <div
                        style={{
                          position: 'absolute',
                          top: '50%',
                          left: '50%',
                          transform: 'translate(-50%, -50%)',
                          zIndex: 1,
                        }}
                      >
                        60%
                      </div>
                      <div>
                        <CircularProgressbar
                          value={60}
                          styles={buildStyles({
                            textColor: '#000',
                            pathColor: '#03A9F4',
                            trailColor: '#D1D5DB',
                          })}
                          className="group-hover:rotate-[360deg] duration-700"
                        />
                      </div>
                    </div>
                  </div>
                  <div className='text-center hover:scale-[102%] transition-transform'>
                    <span className='text-base md:text-lg'>Mandarin</span>
                    <div style={{ position: 'relative', width: '65px', height: '65px' }} className='space-y-2 group'>
                      <div
                        style={{
                          position: 'absolute',
                          top: '50%',
                          left: '50%',
                          transform: 'translate(-50%, -50%)',
                          zIndex: 1,
                        }}
                      >
                        100%
                      </div>
                      <div>
                        <CircularProgressbar
                          value={100}
                          styles={buildStyles({
                            textColor: '#000',
                            pathColor: '#03A9F4',
                            trailColor: '#D1D5DB',
                          })}
                          className="group-hover:rotate-[360deg] duration-700"
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className='bg-gray-100 p-6 rounded-lg hover:scale-[102%] transition-transform'>
                <h4 className='text-base md:text-lg font-semibold mb-2 text-center md:text-left'>Hobbies</h4>
                <div className='grid md:grid-cols-3 grid-cols-2 md:gap-1'>
                  <div className='p-2 rounded-lg hover:scale-[102%] transition-transform'>
                    <p>Basketball</p>
                    <div className='flex '>
                      <div className={`w-4 h-4 rounded-full ${60 >= 20 ? 'bg-blue-300' : 'bg-gray-300'}`}></div>
                      <div className={`w-4 h-4 rounded-full ml-1 ${60 >= 40 ? 'bg-blue-400' : 'bg-gray-300'}`}></div>
                      <div className={`w-4 h-4 rounded-full ml-1 ${60 >= 60 ? 'bg-blue-500' : 'bg-gray-300'}`}></div>
                      <div className={`w-4 h-4 rounded-full ml-1 ${60 >= 80 ? 'bg-blue-600' : 'bg-gray-300'}`}></div>
                      <div className={`w-4 h-4 rounded-full ml-1 ${60 >= 100 ? 'bg-blue-700' : 'bg-gray-300'}`}></div>
                    </div>
                  </div>
                  <div className='p-2 rounded-lg hover:scale-[102%] transition-transform'>
                    <p>Swimming</p>
                    <div className='flex'>
                      <div className={`w-4 h-4 rounded-full ${80 >= 20 ? 'bg-blue-300' : 'bg-gray-300'}`}></div>
                      <div className={`w-4 h-4 rounded-full ml-1 ${80 >= 40 ? 'bg-blue-400' : 'bg-gray-300'}`}></div>
                      <div className={`w-4 h-4 rounded-full ml-1 ${80 >= 60 ? 'bg-blue-500' : 'bg-gray-300'}`}></div>
                      <div className={`w-4 h-4 rounded-full ml-1 ${80 >= 80 ? 'bg-blue-600' : 'bg-gray-300'}`}></div>
                      <div className={`w-4 h-4 rounded-full ml-1 ${80 >= 100 ? 'bg-blue-700' : 'bg-gray-300'}`}></div>
                    </div>
                  </div>
                  <div className='p-2 rounded-lg hover:scale-[102%] transition-transform'>
                    <p>Gym</p>
                    <div className='flex'>
                      <div className={`w-4 h-4 rounded-full ${100 >= 20 ? 'bg-blue-300' : 'bg-gray-300'}`}></div>
                      <div className={`w-4 h-4 rounded-full ml-1 ${100 >= 40 ? 'bg-blue-400' : 'bg-gray-300'}`}></div>
                      <div className={`w-4 h-4 rounded-full ml-1 ${100 >= 60 ? 'bg-blue-500' : 'bg-gray-300'}`}></div>
                      <div className={`w-4 h-4 rounded-full ml-1 ${100 >= 80 ? 'bg-blue-600' : 'bg-gray-300'}`}></div>
                      <div className={`w-4 h-4 rounded-full ml-1 ${100 >= 100 ? 'bg-blue-700' : 'bg-gray-300'}`}></div>
                    </div>
                  </div>
                  <div className='p-2 rounded-lg hover:scale-[102%] transition-transform'>
                    <p>Badminton</p>
                    <div className='flex'>
                      <div className={`w-4 h-4 rounded-full ${100 >= 20 ? 'bg-blue-300' : 'bg-gray-300'}`}></div>
                      <div className={`w-4 h-4 rounded-full ml-1 ${100 >= 40 ? 'bg-blue-400' : 'bg-gray-300'}`}></div>
                      <div className={`w-4 h-4 rounded-full ml-1 ${100 >= 60 ? 'bg-blue-500' : 'bg-gray-300'}`}></div>
                      <div className={`w-4 h-4 rounded-full ml-1 ${100 >= 80 ? 'bg-blue-600' : 'bg-gray-300'}`}></div>
                      <div className={`w-4 h-4 rounded-full ml-1 ${100 >= 100 ? 'bg-blue-700' : 'bg-gray-300'}`}></div>
                    </div>
                  </div>
                  <div className='p-2 rounded-lg hover:scale-[102%] transition-transform'>
                    <p>Table Tennis</p>
                    <div className='flex'>
                      <div className={`w-4 h-4 rounded-full ${40 >= 20 ? 'bg-blue-300' : 'bg-gray-300'}`}></div>
                      <div className={`w-4 h-4 rounded-full ml-1 ${40 >= 40 ? 'bg-blue-400' : 'bg-gray-300'}`}></div>
                      <div className={`w-4 h-4 rounded-full ml-1 ${40 >= 60 ? 'bg-blue-500' : 'bg-gray-300'}`}></div>
                      <div className={`w-4 h-4 rounded-full ml-1 ${40 >= 80 ? 'bg-blue-600' : 'bg-gray-300'}`}></div>
                      <div className={`w-4 h-4 rounded-full ml-1 ${40 >= 100 ? 'bg-blue-700' : 'bg-gray-300'}`}></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section id='projects'>
          <div className='shadow-lg p-6 rounded-xl my-10'>
            <h3 className='text-xl md:text-2xl text-center py-5 text-blue-500 font-bold'> My Hackathons and Real Life Projects</h3>
            <div className='grid md:grid-cols-3 gap-3'>
              <div className='bg-gray-100 p-6 rounded-lg hover:scale-[102%] transition-transform'>
                <h4 className='text-base md:text-lg font-semibold mb-5 text-center'>Odessey Hackathon</h4>
                <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
                  <Image src="/c1.png" alt="React Logo" width={100} height={100} />
                </div>
                <h1 className='text-center mt-2 mb-3'>🏆Special Award🏆</h1>
                <p className='text-center mt-2 mb-3'> Theme: Assisting in mental health improvements</p>
                <NextLink href="Odessey">
                  <div className='flex justify-center'>
                    <p className='bg-blue-500 text-white px-9 py-2 rounded-md hover:scale-[105%] transition-transform'>Details</p>
                  </div>
                </NextLink>
              </div>
              <div className='bg-gray-100 p-6 rounded-lg hover:scale-[102%] transition-transform'>
                <h4 className='text-base md:text-lg font-semibold mb-5 text-center'>Hilti ITC Competition</h4>
                <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
                  <Image src="/c2.png" alt="React Logo" width={100} height={100} />
                </div>
                <h1 className='text-center mt-2 mb-3'>🏆Second Place🏆</h1>
                <p className='text-center mt-2 mb-3'> Theme: E commerce app with XR technologies</p>
                <NextLink href="/Hilti">
                  <div className='flex justify-center'>
                    <p className='bg-blue-500 text-white px-9 py-2 rounded-md hover:scale-[105%] transition-transform'>Details</p>
                  </div>
                </NextLink>
              </div>
              <div className='bg-gray-100 p-6 rounded-lg hover:scale-[102%] transition-transform'>
                <h4 className='text-base md:text-lg font-semibold mb-5 text-center'>RHB Get Your Hack On: ASEAN</h4>
                <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
                  <Image src="/c3.png" alt="React Logo" width={100} height={100} />
                </div>
                <h1 className='text-center mt-2 mb-3'>🧠Participant🧠</h1>
                <p className='text-center mt-2 mb-3'> Theme: Help young adult to develop financial literacy</p>
                <NextLink href="/Rhb">
                  <div className='flex justify-center'>
                    <p className='bg-blue-500 text-white px-9 py-2 rounded-md hover:scale-[105%] transition-transform'>Details</p>
                  </div>
                </NextLink>
              </div>
              <div className='bg-gray-100 p-6 rounded-lg hover:scale-[102%] transition-transform'>
                <h4 className='text-base md:text-lg font-semibold mb-5 text-center'>Nutox Microsite</h4>
                <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
                  <Image src="/nutox.png" alt="React Logo" width={100} height={100} />
                </div>
                <h1 className='text-center mt-2 mb-3'>💄Beauty Product💄</h1>
                <p className='text-center mt-2 mb-3'> Theme: Participate Juicy Glow Girl Skin Girl Search to Win Prize</p>
                <NextLink href="https://myc.my/nutoxjuicyglowgirl" target='_blank'>
                  <div className='flex justify-center'>
                    <p className='bg-blue-500 text-white px-9 py-2 rounded-md hover:scale-[105%] transition-transform'>View Microsite</p>
                  </div>
                </NextLink>
              </div>
              <div className='bg-gray-100 p-6 rounded-lg hover:scale-[102%] transition-transform'>
                <h4 className='text-base md:text-lg font-semibold mb-5 text-center'>Spritzer Microsite</h4>
                <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
                  <Image src="/spritzer.png" alt="React Logo" width={70} height={70} />
                </div>
                <h1 className='text-center mt-2 mb-3'>🍾Drinking Product🍾</h1>
                <p className='text-center mt-2 mb-3'> Theme: Participate and Win Free Hot Air Ballon or E Kart Riding Ticket</p>
                <NextLink href="https://myc.my/sotingeyouthtopia" target='_blank'>
                  <div className='flex justify-center'>
                    <p className='bg-blue-500 text-white px-9 py-2 rounded-md hover:scale-[105%] transition-transform'>View Microsite</p>
                  </div>
                </NextLink>
              </div>
              <div className='bg-gray-100 p-6 rounded-lg hover:scale-[102%] transition-transform'>
                <h4 className='text-base md:text-lg font-semibold mb-5 text-center'>Hiruscar Microsite & AR Filter</h4>
                <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
                  <Image src="/hiruscar.png" alt="React Logo" width={150} height={150} />
                </div>
                <h1 className='text-center mt-2 mb-3'>💄Beauty Product💄</h1>
                <p className='text-center mt-2 mb-8'> Theme: Participate and Get Free Voucher</p>
                <div className='flex space-x-3 justify-center'>
                  <NextLink href="https://myc.my/hiruscar-qr-station" target='_blank' >
                    <p className='bg-blue-500 text-white px-5 py-2 rounded-md hover:scale-[105%] transition-transform'>View Microsite</p>
                  </NextLink>
                  <NextLink href="https://www.instagram.com/ar/3651541968413397/" target='_blank' className='flex space-x-3'>
                    <p className='bg-blue-500 text-white px-5 py-2 rounded-md hover:scale-[105%] transition-transform'>View AR Filter</p>
                  </NextLink>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section id='skills'>
          <div className='shadow-lg p-5 rounded-xl my-10'>
            <h3 className='text-xl md:text-2xl text-center py-5 text-blue-500 font-bold'> My Skills and Interests</h3>
            <div className='grid md:grid-cols-3 gap-3'>
              <div className='bg-gray-100 p-6 rounded-lg hover:scale-[102%] transition-transform'>
                <h4 className='text-base md:text-lg font-semibold mb-5 text-center md:text-left'>Front End Development</h4>
                <div className="transition-transform transform-gpu hover:scale-[102%] group text-base md:text-lg">
                  <p className=" py-2 ">
                    <Image src="/angular.png" alt="" className="inline-block w-8 h-8 mr-2" width={240} height={240} />
                    Angular <span className="text-sm hidden transition-transform transform-gpu group-hover:inline-block"> (70%) </span>
                  </p>
                  <div className="w-full bg-gray-200 rounded-full h-2 msd:h-3 dark:bg-gray-700 relative group">
                    <div
                      className="bg-blue-500 h-2 md:h-3 rounded-full"
                      style={{ width: "70%" }}
                    ></div>
                  </div>
                </div>
                <div className="transition-transform transform-gpu hover:scale-[102%] group text-base md:text-lg">
                  <p className=" py-2 ">
                    <Image src="/React.png" alt="" className="inline-block w-8 h-8 mr-2" width={240} height={240} />
                    React <span className="text-sm hidden transition-transform transform-gpu group-hover:inline-block"> (50%) </span>
                  </p>
                  <div className="w-full bg-gray-200 rounded-full h-2 md:h-3 dark:bg-gray-700 mb-2 relative group">
                    <div
                      className="bg-blue-500 h-2 md:h-3 rounded-full"
                      style={{ width: "50%" }}
                    ></div>
                  </div>
                </div>
                <div className="transition-transform transform-gpu hover:scale-[102%] group text-base md:text-lg">
                  <p className=" py-2 ">
                    <Image src="/nextjs.png" alt="" className="inline-block w-8 h-8 mr-2" width={240} height={240} />
                    Next.js <span className="text-sm hidden transition-transform transform-gpu group-hover:inline-block"> (50%) </span>
                  </p>
                  <div className="w-full bg-gray-200 rounded-full h-2 md:h-3 dark:bg-gray-700 mb-2 relative group">
                    <div
                      className="bg-blue-500 h-2 md:h-3 rounded-full"
                      style={{ width: "50%" }}
                    ></div>
                  </div>
                </div>
              </div>
              <div className='bg-gray-100 p-6 rounded-lg transition-transform hover:scale-[102%]'>
                <h4 className='text-base md:text-lg font-semibold mb-5 text-center md:text-left'>Back End Development</h4>
                <div className="transition-transform transform-gpu hover:scale-[102%] group text-base md:text-lg">
                  <p className=" py-2 ">
                    <Image src="/spring-boot.png" alt="" className="inline-block w-8 h-8 mr-2" width={240} height={240} />
                    Spring Boot <span className="text-sm hidden transition-transform transform-gpu group-hover:inline-block"> (60%) </span>
                  </p>
                  <div className="w-full bg-gray-200 rounded-full h-2 md:h-3 dark:bg-gray-700 mb-2 relative group">
                    <div
                      className="bg-blue-500 h-2 md:h-3 rounded-full"
                      style={{ width: "60%" }}
                    ></div>
                  </div>
                </div>
                <div className="transition-transform transform-gpu hover:scale-[102%] group text-base md:text-lg">
                  <p className=" py-2 ">
                    <Image src="/nodejs.png" alt="" className="inline-block w-8 h-8 mr-2" width={240} height={240} />
                    Node.js <span className="text-sm hidden transition-transform transform-gpu group-hover:inline-block"> (50%) </span>
                  </p>
                  <div className="w-full bg-gray-200 rounded-full h-2 md:h-3 dark:bg-gray-700 mb-2 relative group">
                    <div
                      className="bg-blue-500 h-2 md:h-3 rounded-full"
                      style={{ width: "50%" }}
                    ></div>
                  </div>
                </div>
                {/* <div className="transition-transform transform-gpu hover:scale-[102%] group text-base md:text-lg">
                  <p className=" py-2 ">
                    <Image src="/nestjs.png" alt="" className="inline-block w-8 h-8 mr-2" width={240} height={240} />
                    Nest.js <span className="text-sm hidden transition-transform transform-gpu group-hover:inline-block"> (0%) </span>
                  </p>
                  <div className="w-full bg-gray-200 rounded-full h-2 md:h-3 dark:bg-gray-700 mb-2 relative group">
                    <div
                      className="bg-blue-500 h-2 md:h-3 rounded-full"
                      style={{ width: "0%" }}
                    ></div>
                  </div>
                </div> */}
                {/* <div className="transition-transform transform-gpu hover:scale-[102%] group text-base md:text-lg">
                  <p className=" py-2 ">
                    <Image src="/flask.png" alt="" className="inline-block w-8 h-8 mr-2" width={240} height={240} />
                    Flask <span className="text-sm hidden transition-transform transform-gpu group-hover:inline-block"> (0%) </span>
                  </p>
                  <div className="w-full bg-gray-200 rounded-full h-2 md:h-3 dark:bg-gray-700 relative group">
                    <div
                      className="bg-blue-500 h-2 md:h-3 rounded-full"
                      style={{ width: "0%" }}
                    ></div>
                  </div>
                </div> */}
              </div>
              <div className='bg-gray-100 p-6 rounded-lg hover:scale-[102%] transition-transform'>
                <h4 className='text-base md:text-lg font-semibold mb-5 text-center md:text-left'>App Development</h4>
                <div className="transition-transform transform-gpu hover:scale-[102%] group text-base md:text-lg">
                  <p className=" py-2 ">
                    <Image src="/React.png" alt="" className="inline-block w-8 h-8 mr-2" width={240} height={240} />
                    React Native <span className="text-sm hidden transition-transform transform-gpu group-hover:inline-block"> (60%) </span>
                  </p>
                  <div className="w-full bg-gray-200 rounded-full h-2 md:h-3 dark:bg-gray-700 mb-2 relative group">
                    <div
                      className="bg-blue-500 h-2 md:h-3 rounded-full"
                      style={{ width: "60%" }}
                    ></div>
                  </div>
                </div>
                <div className="transition-transform transform-gpu hover:scale-[102%] group text-base md:text-lg">
                  <p className=" py-2 ">
                    <Image src="/flutter.png" alt="" className="inline-block w-8 h-8 mr-2" width={240} height={240} />
                    Flutter <span className="text-sm hidden transition-transform transform-gpu group-hover:inline-block"> (30%) </span>
                  </p>
                  <div className="w-full bg-gray-200 rounded-full h-2 md:h-3 dark:bg-gray-700 mb-2 relative group">
                    <div
                      className="bg-blue-500 h-2 md:h-3 rounded-full"
                      style={{ width: "30%" }}
                    ></div>
                  </div>
                </div>
              </div>
              <div className='bg-gray-100 p-6 rounded-lg hover:scale-[102%] transition-transform'>
                <h4 className='text-base md:text-lg font-semibold mb-5 text-center md:text-left'>Languages</h4>
                <div className="transition-transform transform-gpu hover:scale-[102%] group text-base md:text-lg">
                  <p className=" py-2 ">
                    <Image src="/ts.png" alt="" className="inline-block w-8 h-8 mr-2" width={240} height={240} />
                    Typescript <span className="text-sm hidden transition-transform transform-gpu group-hover:inline-block"> (70%) </span>
                  </p>
                  <div className="w-full bg-gray-200 rounded-full h-2 md:h-3 dark:bg-gray-700 mb-2 relative group">
                    <div
                      className="bg-blue-500 h-2 md:h-3 rounded-full"
                      style={{ width: "70%" }}
                    ></div>
                  </div>
                </div>
                <div className="transition-transform transform-gpu hover:scale-[102%] group text-base md:text-lg">
                  <p className=" py-2 ">
                    <Image src="/java.png" alt="" className="inline-block w-8 h-8 mr-2" width={240} height={240} />
                    Java <span className="text-sm hidden transition-transform transform-gpu group-hover:inline-block"> (60%) </span>
                  </p>
                  <div className="w-full bg-gray-200 rounded-full h-2 md:h-3 dark:bg-gray-700 mb-2 relative group">
                    <div
                      className="bg-blue-500 h-2 md:h-3 rounded-full"
                      style={{ width: "60%" }}
                    ></div>
                  </div>
                </div>
                <div className="transition-transform transform-gpu hover:scale-[102%] group text-base md:text-lg">
                  <p className=" py-2 ">
                    <Image src="/js.png" alt="" className="inline-block w-8 h-8 mr-2" width={240} height={240} />
                    Javascript <span className="text-sm hidden transition-transform transform-gpu group-hover:inline-block"> (70%) </span>
                  </p>
                  <div className="w-full bg-gray-200 rounded-full h-2 md:h-3 dark:bg-gray-700 mb-2 relative group">
                    <div
                      className="bg-blue-500 h-2 md:h-3 rounded-full"
                      style={{ width: "70%" }}
                    ></div>
                  </div>
                </div>
              </div>
              <div className='bg-gray-100 p-6 rounded-lg hover:scale-[102%] transition-transform'>
                <h4 className='text-base md:text-lg font-semibold mb-5 text-center md:text-left'>Tools</h4>
                <div className="transition-transform transform-gpu hover:scale-[102%] group text-base md:text-lg">
                  <p className=" py-2 ">
                    <Image src="/git.png" alt="" className="inline-block w-8 h-8 mr-2" width={240} height={240} />
                    Git <span className="text-sm hidden transition-transform transform-gpu group-hover:inline-block"> (60%) </span>
                  </p>
                  <div className="w-full bg-gray-200 rounded-full h-2 md:h-3 dark:bg-gray-700 mb-2 relative group">
                    <div
                      className="bg-blue-500 h-2 md:h-3 rounded-full"
                      style={{ width: "60%" }}
                    ></div>
                  </div>
                </div>
                <div className="transition-transform transform-gpu hover:scale-[102%] group text-base md:text-lg">
                  <p className=" py-2 ">
                    <Image src="/gitlab.png" alt="" className="inline-block w-8 h-8 mr-2" width={240} height={240} />
                    GitLab <span className="text-sm hidden transition-transform transform-gpu group-hover:inline-block"> (60%) </span>
                  </p>
                  <div className="w-full bg-gray-200 rounded-full h-2 md:h-3 dark:bg-gray-700 relative group">
                    <div
                      className="bg-blue-500 h-2 md:h-3 rounded-full"
                      style={{ width: "60%" }}
                    ></div>
                  </div>
                </div>
              </div>
              <div className='bg-gray-100 p-6 rounded-lg hover:scale-[102%] transition-transform'>
                <h4 className='text-base md:text-lg font-semibold mb-5 text-center md:text-left'>Extra</h4>
                <div className="transition-transform transform-gpu hover:scale-[102%] group text-base md:text-lg">
                  <p className=" py-2 ">
                    <Image src="/ag.png" alt="" className="inline-block w-8 h-8 mr-2" width={240} height={240} />
                    Agile <span className="text-sm hidden transition-transform transform-gpu group-hover:inline-block"> (70%) </span>
                  </p>
                  <div className="w-full bg-gray-200 rounded-full h-2 md:h-3 dark:bg-gray-700 mb-2 relative group">
                    <div
                      className="bg-blue-500 h-2 md:h-3 rounded-full"
                      style={{ width: "70%" }}
                    ></div>
                  </div>
                </div>
                <div className="transition-transform transform-gpu hover:scale-[102%] group text-base md:text-lg">
                  <p className=" py-2 ">
                    <Image src="/ml.png" alt="" className="inline-block w-8 h-8 mr-2" width={240} height={240} />
                    Machine Learning <span className="text-sm hidden transition-transform transform-gpu group-hover:inline-block"> (90%) </span>
                  </p>
                  <div className="w-full bg-gray-200 rounded-full h-2 md:h-3 dark:bg-gray-700 mb-2 relative group">
                    <div
                      className="bg-blue-500 h-2 md:h-3 rounded-full"
                      style={{ width: "90%" }}
                    ></div>
                  </div>
                </div>
                <div className="transition-transform transform-gpu hover:scale-[102%] group text-base md:text-lg">
                  <p className=" py-2 ">
                    <Image src="/nlp.png" alt="" className="inline-block w-8 h-8 mr-2" width={240} height={240} />
                    Natural Language Processing <span className="text-sm hidden transition-transform transform-gpu group-hover:inline-block"> (80%) </span>
                  </p>
                  <div className="w-full bg-gray-200 rounded-full h-2 md:h-3 dark:bg-gray-700 relative group">
                    <div
                      className="bg-blue-500 h-2 md:h-3 rounded-full"
                      style={{ width: "80%" }}
                    ></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section id='life'>
          <div className='shadow-lg p-6 rounded-xl my-10'>
            <h3 className='text-xl md:text-2xl text-center py-5 text-blue-500 font-bold'>Some Meaningful Photos In My Life</h3>
            <div className='grid md:grid-cols-3 gap-3'>
              <div className='group rounded-lg [perspective:1000px]'>
                <div className=' transition-all duration-500 [transform-style:preserve-3d] group-hover:[transform:rotateY(180deg)]'>
                  <div >
                    <Image src="/img6.jpg" alt="" className="h-full w-full rounded-xl object-cover shadow-xl shadow-black/40" width={200} height={200} />
                  </div>
                  <div className='absolute inset-0 h-full w-full rounded-xl bg-black/80 px-12 text-center text-slate-200 [transform:rotateY(180deg)] [backface-visibility:hidden]'>
                    <div className='flex min-h-full flex-col items-center justify-center'>
                      <h1 className='text-lg md:text-xl lg:text-3xl font-bold'>Friendship Trip</h1>
                      <p className='text-base md:text-lg'>Krabi Thailand</p>
                      <p className='text-base md:text-lg'>Celebrate New Year Eve</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className='group rounded-lg [perspective:1000px]'>
                <div className=' transition-all duration-500 [transform-style:preserve-3d] group-hover:[transform:rotateY(180deg)]'>
                  <div >
                    <Image src="/img5.jpg" alt="" className="h-full w-full rounded-xl object-cover shadow-xl shadow-black/40" width={200} height={200} />
                  </div>
                  <div className='absolute inset-0 h-full w-full rounded-xl bg-black/80 px-12 text-center text-slate-200 [transform:rotateY(180deg)] [backface-visibility:hidden]'>
                    <div className='flex min-h-full flex-col items-center justify-center'>
                      <h1 className='text-lg md:text-xl lg:text-3xl font-bold'>MYC! Group Photo</h1>
                      <p className='text-base md:text-lg'>Intern as Full Stack Developer</p>
                      <p className='text-base md:text-lg'>Start: 16th Aug 2023</p>
                      <p className='text-base md:text-lg'>End: 15th Dec 2023</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className='group rounded-lg [perspective:1000px]'>
                <div className=' transition-all duration-500 [transform-style:preserve-3d] group-hover:[transform:rotateY(180deg)]'>
                  <div >
                    <Image src="/img3.jpg" alt="" className="h-full w-full rounded-xl object-cover shadow-xl shadow-black/40" width={200} height={200} />
                  </div>
                  <div className='absolute inset-0 h-full w-full rounded-xl bg-black/80 px-12 text-center text-slate-200 [transform:rotateY(180deg)] [backface-visibility:hidden]'>
                    <div className='flex min-h-full flex-col items-center justify-center'>
                      <h1 className='text-lg md:text-xl lg:text-3xl font-bold'>Family Photo</h1>
                      <p className='text-base md:text-lg'>Trip to New Zealand</p>
                      <p className='text-base md:text-lg'>Good Experience</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* embedded youtube video */}
        {/* <section>
          <div className='shadow-lg p-5 rounded-xl my-10'>
            <h3 className='text-xl md:text-2xl text-center py-5 text-blue-500 font-bold'>My Intriguing Project in Uni Life</h3>
            <div className="justify-center items-center flex video-container" >
              <iframe
                src="https://www.youtube.com/embed/mOGdG9XCv40?autoplay=1&mute=1"
                title="Embedded YouTube Video"
                allowFullScreen
              />
            </div>
          </div>
        </section> */}

        {/* scrolling up arrow */}
        {scrolling && (
          <div
            className="fixed bottom-5 right-5 md:bottom-5 md:right-10 cursor-pointer bg-blue-500 rounded-full p-2 md:p-4"
            onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
          >
            <FaArrowUp className="text-white text-xl" />
          </div>
        )}

        <footer>
          <div className='flex items-center justify-center'>
            <a href="https://www.instagram.com/qiqian1227/" target="_blank" rel="noopener noreferrer" className='md:mt-2 mt-1 md:md-2 hover:scale-[110%]  transition-transform'><AiFillInstagram size={30} /></a>
            <a href="https://www.facebook.com/qiqianchai/" target="_blank" rel="noopener noreferrer" className='md:mt-2 mt-1 md:md-2 md:ml-10 ml-10 hover:scale-[110%]  transition-transform'><AiFillFacebook size={30} /></a>
            <a href="https://www.linkedin.com/in/chai-qi-qian-a5094520a/" target="_blank" rel="noopener noreferrer" className='md:mt-2 mt-1 md:md-2 md:ml-10 ml-10 hover:scale-[110%]  transition-transform'><AiFillLinkedin size={30} /></a>
          </div>
          <div className='text-lg text-center items-center justify-center mt-5 mb-5'>
            <p >© 2023 No rights reserved. Celebrating Freedom in Our World 🌍🕊️</p>
          </div>
        </footer>

      </main>
    </div >
  )
}